config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :annotations
  resources :placements
  resources :galleries
  resources :artworks
  resources :collaborations
  resources :collectives
  resources :artists

  root 'galleries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collective.rb
class Collective < ApplicationRecord
end

app/controllers/collectives_controller.rb
class CollectivesController < ApplicationController
  before_action :set_collective, only: [:show, :edit, :update, :destroy]

  # GET /collectives
  # GET /collectives.json
  def index
    @collectives = Collective.all
  end

  # GET /collectives/1
  # GET /collectives/1.json
  def show
  end

  # GET /collectives/new
  def new
    @collective = Collective.new
  end

  # GET /collectives/1/edit
  def edit
  end

  # POST /collectives
  # POST /collectives.json
  def create
    @collective = Collective.new(collective_params)

    respond_to do |format|
      if @collective.save
        format.html { redirect_to @collective, notice: 'Collective was successfully created.' }
        format.json { render :show, status: :created, location: @collective }
      else
        format.html { render :new }
        format.json { render json: @collective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collectives/1
  # PATCH/PUT /collectives/1.json
  def update
    respond_to do |format|
      if @collective.update(collective_params)
        format.html { redirect_to @collective, notice: 'Collective was successfully updated.' }
        format.json { render :show, status: :ok, location: @collective }
      else
        format.html { render :edit }
        format.json { render json: @collective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collectives/1
  # DELETE /collectives/1.json
  def destroy
    @collective.destroy
    respond_to do |format|
      format.html { redirect_to collectives_url, notice: 'Collective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collective
      @collective = Collective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collective_params
      params.require(:collective).permit(:name, :created, :broke_up, :bio, :style)
    end
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/views/collectives/_form.html.erb
<%= form_with(model: collective, local: true) do |form| %>
  <% if collective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collective.errors.count, "error") %> prohibited this collective from being saved:</h2>

      <ul>
      <% collective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :created %>
    <%= form.date_select :created %>
  </div>

  <div class="field">
    <%= form.label :broke_up %>
    <%= form.date_select :broke_up %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collectives/edit.html.erb
<h1>Editing Collective</h1>

<%= render 'form', collective: @collective %>

<%= link_to 'Show', @collective %> |
<%= link_to 'Back', collectives_path %>

app/views/collectives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collectives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
      <th>Broke up</th>
      <th>Bio</th>
      <th>Style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collectives.each do |collective| %>
      <tr>
        <td><%= collective.name %></td>
        <td><%= collective.created %></td>
        <td><%= collective.broke_up %></td>
        <td><%= collective.bio %></td>
        <td><%= collective.style %></td>
        <td><%= link_to 'Show', collective %></td>
        <td><%= link_to 'Edit', edit_collective_path(collective) %></td>
        <td><%= link_to 'Destroy', collective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collective', new_collective_path %>

app/views/collectives/new.html.erb
<h1>New Collective</h1>

<%= render 'form', collective: @collective %>

<%= link_to 'Back', collectives_path %>

app/views/collectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collective.name %>
</p>

<p>
  <strong>Created:</strong>
  <%= @collective.created %>
</p>

<p>
  <strong>Broke up:</strong>
  <%= @collective.broke_up %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @collective.bio %>
</p>

<p>
  <strong>Style:</strong>
  <%= @collective.style %>
</p>

<%= link_to 'Edit', edit_collective_path(@collective) %> |
<%= link_to 'Back', collectives_path %>