config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :annotations
  resources :placements
  resources :galleries
  resources :artworks
  resources :collaborations
  resources :collectives
  resources :artists

  root 'galleries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collaboration, only: [:show, :edit, :update, :destroy]

  # GET /collaborations
  # GET /collaborations.json
  def index
    @collaborations = Collaboration.all
  end

  # GET /collaborations/1
  # GET /collaborations/1.json
  def show
  end

  # GET /collaborations/new
  def new
    @collaboration = Collaboration.new
  end

  # GET /collaborations/1/edit
  def edit
  end

  # POST /collaborations
  # POST /collaborations.json
  def create
    @collaboration = Collaboration.new(collaboration_params)

    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to @collaboration, notice: 'Collaboration was successfully created.' }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { render :new }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborations/1
  # PATCH/PUT /collaborations/1.json
  def update
    respond_to do |format|
      if @collaboration.update(collaboration_params)
        format.html { redirect_to @collaboration, notice: 'Collaboration was successfully updated.' }
        format.json { render :show, status: :ok, location: @collaboration }
      else
        format.html { render :edit }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborations/1
  # DELETE /collaborations/1.json
  def destroy
    @collaboration.destroy
    respond_to do |format|
      format.html { redirect_to collaborations_url, notice: 'Collaboration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collaboration_params
      params.require(:collaboration).permit(:artist_id, :collective_id)
    end
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/_form.html.erb
<%= form_with(model: collaboration, local: true) do |form| %>
  <% if collaboration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collaboration.errors.count, "error") %> prohibited this collaboration from being saved:</h2>

      <ul>
      <% collaboration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.number_field :artist_id %>
  </div>

  <div class="field">
    <%= form.label :collective_id %>
    <%= form.number_field :collective_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collaborations/edit.html.erb
<h1>Editing Collaboration</h1>

<%= render 'form', collaboration: @collaboration %>

<%= link_to 'Show', @collaboration %> |
<%= link_to 'Back', collaborations_path %>

app/views/collaborations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collaborations</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Collective</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborations.each do |collaboration| %>
      <tr>
        <td><%= collaboration.artist_id %></td>
        <td><%= collaboration.collective_id %></td>
        <td><%= link_to 'Show', collaboration %></td>
        <td><%= link_to 'Edit', edit_collaboration_path(collaboration) %></td>
        <td><%= link_to 'Destroy', collaboration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collaboration', new_collaboration_path %>

app/views/collaborations/new.html.erb
<h1>New Collaboration</h1>

<%= render 'form', collaboration: @collaboration %>

<%= link_to 'Back', collaborations_path %>

app/views/collaborations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @collaboration.artist_id %>
</p>

<p>
  <strong>Collective:</strong>
  <%= @collaboration.collective_id %>
</p>

<%= link_to 'Edit', edit_collaboration_path(@collaboration) %> |
<%= link_to 'Back', collaborations_path %>