config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :annotations
  resources :placements
  resources :galleries
  resources :artworks
  resources :collaborations
  resources :collectives
  resources :artists

  root 'galleries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/annotation.rb
class Annotation < ApplicationRecord
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: [:show, :edit, :update, :destroy]

  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.all
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
  end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to @annotation, notice: 'Annotation was successfully created.' }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1
  # PATCH/PUT /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to @annotation, notice: 'Annotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1
  # DELETE /annotations/1.json
  def destroy
    @annotation.destroy
    respond_to do |format|
      format.html { redirect_to annotations_url, notice: 'Annotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annotation_params
      params.require(:annotation).permit(:body, :user_id, :gallery_id, :order)
    end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/views/annotations/_form.html.erb
<%= form_with(model: annotation, local: true) do |form| %>
  <% if annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% annotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :gallery_id %>
    <%= form.number_field :gallery_id %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing Annotation</h1>

<%= render 'form', annotation: @annotation %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Annotations</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Gallery</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= annotation.body %></td>
        <td><%= annotation.user_id %></td>
        <td><%= annotation.gallery_id %></td>
        <td><%= annotation.order %></td>
        <td><%= link_to 'Show', annotation %></td>
        <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
        <td><%= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New Annotation</h1>

<%= render 'form', annotation: @annotation %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @annotation.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @annotation.user_id %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @annotation.gallery_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @annotation.order %>
</p>

<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>